// ============================================================
// TravelOps — Mock Travel Data
// ============================================================

import type {
  TravelRoute,
  AgentActivity,
  BrowserAgentEvent,
  SearchStats,
  TripHistoryItem,
} from '@/types/travel';

export const MOCK_ROUTES: TravelRoute[] = [
  {
    id: 'route-1',
    status: 'recommended',
    primaryMode: 'flight',
    segments: [
      {
        mode: 'flight',
        from: 'Kolkata (CCU)',
        to: 'Delhi (DEL)',
        departure: '04:15 AM',
        arrival: '07:10 AM',
        carrier: 'IndiGo 6E-204',
        duration: '2h 55m',
      },
      {
        mode: 'cab',
        from: 'Delhi Airport (T2)',
        to: 'Destination',
        departure: '07:40 AM',
        arrival: '08:10 AM',
        duration: '30m',
      },
    ],
    totalPrice: 7200,
    currency: '₹',
    finalArrival: '07:10 AM',
    travelTime: '2h 55m',
    riskLevel: 'LOW',
    score: 94,
    transfers: 0,
    safetyBuffer: '2h 50m',
    deadlineMet: true,
    recommendationReasons: [
      'Within ₹8,000 budget',
      'Arrives before 10:00 AM deadline',
      'Direct flight — no connections',
      'Lowest connection risk',
      '2h 50m safety buffer',
    ],
  },
  {
    id: 'route-2',
    status: 'rejected',
    primaryMode: 'train',
    segments: [
      {
        mode: 'train',
        from: 'Howrah Station',
        to: 'New Delhi Station',
        departure: '07:05 PM',
        arrival: '11:30 AM',
        carrier: 'Rajdhani Express 12301',
        duration: '16h 25m',
      },
    ],
    totalPrice: 3400,
    currency: '₹',
    finalArrival: '11:30 AM',
    travelTime: '16h 25m',
    riskLevel: 'LOW',
    score: 41,
    transfers: 0,
    safetyBuffer: '-1h 30m',
    deadlineMet: false,
    rejectionReason: 'Arrives 1h 30m after your 10:00 AM deadline.',
  },
  {
    id: 'route-3',
    status: 'viable',
    primaryMode: 'flight',
    segments: [
      {
        mode: 'flight',
        from: 'Kolkata (CCU)',
        to: 'Mumbai (BOM)',
        departure: '01:20 AM',
        arrival: '04:05 AM',
        carrier: 'Air India AI-771',
        duration: '2h 45m',
        transferTime: '40m layover',
      },
      {
        mode: 'flight',
        from: 'Mumbai (BOM)',
        to: 'Delhi (DEL)',
        departure: '04:45 AM',
        arrival: '06:55 AM',
        carrier: 'Air India AI-102',
        duration: '2h 10m',
      },
    ],
    totalPrice: 6800,
    currency: '₹',
    finalArrival: '09:15 AM',
    travelTime: '8h 55m',
    riskLevel: 'MEDIUM',
    score: 72,
    transfers: 1,
    safetyBuffer: '45m',
    deadlineMet: true,
    recommendationReasons: [
      'Meets 10:00 AM deadline',
      'Within ₹8,000 budget',
    ],
    rejectionReason: 'High connection risk — only 40 min layover in Mumbai.',
  },
];

export const MOCK_REPLANNED_ROUTES: TravelRoute[] = [
  {
    id: 'replan-1',
    status: 'recommended',
    primaryMode: 'flight',
    segments: [
      {
        mode: 'flight',
        from: 'Kolkata (CCU)',
        to: 'Mumbai (BOM)',
        departure: '01:20 AM',
        arrival: '04:05 AM',
        carrier: 'Air India AI-771',
        duration: '2h 45m',
        transferTime: '40m layover',
      },
      {
        mode: 'flight',
        from: 'Mumbai (BOM)',
        to: 'Delhi (DEL)',
        departure: '04:45 AM',
        arrival: '06:55 AM',
        carrier: 'Air India AI-102',
        duration: '2h 10m',
      },
    ],
    totalPrice: 6800,
    currency: '₹',
    finalArrival: '09:15 AM',
    travelTime: '8h 55m',
    riskLevel: 'MEDIUM',
    score: 81,
    transfers: 1,
    safetyBuffer: '45m',
    deadlineMet: true,
    recommendationReasons: [
      'Original flight now arrives after deadline',
      'Only alternative meeting 10:00 AM deadline',
      'Within ₹8,000 budget',
      '45 min safety buffer',
    ],
  },
  {
    id: 'replan-2',
    status: 'rejected',
    primaryMode: 'train',
    segments: [
      {
        mode: 'train',
        from: 'Howrah Station',
        to: 'New Delhi Station',
        departure: '07:05 PM',
        arrival: '11:30 AM',
        carrier: 'Rajdhani Express 12301',
        duration: '16h 25m',
      },
    ],
    totalPrice: 3400,
    currency: '₹',
    finalArrival: '11:30 AM',
    travelTime: '16h 25m',
    riskLevel: 'LOW',
    score: 38,
    transfers: 0,
    safetyBuffer: '-1h 30m',
    deadlineMet: false,
    rejectionReason: 'Misses deadline by 1h 30m.',
  },
];

export const MOCK_ACTIVITIES: AgentActivity[] = [
  { timestamp: '09:31:02', message: 'Understanding your travel constraints', type: 'info' },
  { timestamp: '09:31:04', message: 'Opened flight search engine', type: 'search' },
  { timestamp: '09:31:06', message: 'Found 14 flights — Kolkata → Delhi', type: 'found' },
  { timestamp: '09:31:08', message: 'Opened train search engine', type: 'search' },
  { timestamp: '09:31:11', message: 'Found 7 trains — Howrah → New Delhi', type: 'found' },
  { timestamp: '09:31:13', message: 'Checked nearby departure points', type: 'search' },
  { timestamp: '09:31:15', message: '17 routes evaluated in total', type: 'info' },
  { timestamp: '09:31:17', message: 'Filtering routes by budget (≤ ₹8,000)', type: 'info' },
  { timestamp: '09:31:18', message: '4 routes eliminated — over budget', type: 'eliminated' },
  { timestamp: '09:31:19', message: 'Checking deadline compliance (10:00 AM)', type: 'info' },
  { timestamp: '09:31:20', message: '7 routes eliminated — miss deadline', type: 'eliminated' },
  { timestamp: '09:31:21', message: 'Evaluating connection risk scores', type: 'info' },
  { timestamp: '09:31:22', message: '3 viable routes selected', type: 'selected' },
  { timestamp: '09:31:23', message: 'Final recommendation generated', type: 'selected' },
];

export const MOCK_BROWSER_EVENTS: BrowserAgentEvent[] = [
  { timestamp: '09:31:04', tab: 'flight', action: 'Navigating to flight search', status: 'searching' },
  { timestamp: '09:31:05', tab: 'flight', action: 'Searching: Kolkata → Delhi', detail: 'Tomorrow, 1 adult', status: 'searching' },
  { timestamp: '09:31:06', tab: 'flight', action: 'Found 14 results', detail: 'Extracting prices and times...', status: 'extracting' },
  { timestamp: '09:31:07', tab: 'flight', action: 'Extracted 14 flight options', status: 'done' },
  { timestamp: '09:31:08', tab: 'rail', action: 'Navigating to rail search', status: 'searching' },
  { timestamp: '09:31:09', tab: 'rail', action: 'Searching: Howrah → New Delhi', detail: 'All trains', status: 'searching' },
  { timestamp: '09:31:11', tab: 'rail', action: 'Found 7 train routes', detail: 'Extracting schedules...', status: 'extracting' },
  { timestamp: '09:31:12', tab: 'rail', action: 'Extracted 7 train options', status: 'done' },
  { timestamp: '09:31:13', tab: 'bus', action: 'Checking bus routes', detail: 'Kolkata → Delhi', status: 'searching' },
  { timestamp: '09:31:14', tab: 'bus', action: 'No viable bus routes (>24h travel)', status: 'done' },
  { timestamp: '09:31:15', tab: 'maps', action: 'Checking transfer distances', status: 'done' },
  { timestamp: '09:31:16', tab: 'weather', action: 'Checking weather delays', detail: 'No disruptions found', status: 'done' },
];

export const MOCK_STATS: SearchStats = {
  totalFound: 17,
  eliminated: 11,
  viable: 6,
  recommended: 3,
};

export const MOCK_TRIP_HISTORY: TripHistoryItem[] = [
  {
    id: 'trip-1',
    origin: 'Kolkata',
    destination: 'Delhi',
    crisisType: 'flight_cancelled',
    status: 'resolved',
    finalPrice: 7200,
    currency: '₹',
    finalArrival: '7:10 AM',
    date: '2026-08-18',
  },
  {
    id: 'trip-2',
    origin: 'Mumbai',
    destination: 'Bengaluru',
    crisisType: 'missed_connection',
    status: 'resolved',
    finalPrice: 5800,
    currency: '₹',
    finalArrival: '3:45 PM',
    date: '2026-08-10',
  },
  {
    id: 'trip-3',
    origin: 'Delhi',
    destination: 'Jaipur',
    crisisType: 'train_delayed',
    status: 'replanned',
    finalPrice: 2100,
    currency: '₹',
    finalArrival: '11:20 AM',
    date: '2026-08-05',
  },
];
